### ISSUE TITLE
Can't seek on Samsung

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#251]
probably already fixed

**Comment by SimonSimCity** [comment]
This issue doesn't seem to be limited to Samsung. I had it today as well.

Device model: ONEPLUS A5010
App version 1.67.0

I had it today with the latest "fra Kåre" and noticed it after I paused the track and tried to go back - when resuming it jumped back. It worked again after restarting the app... For listening to Fra Kare, I opened the App via the notification - maybe that had something to say ... Couldn't retry, that because have no bmm-notifications left 😁

**Comment by kkuepper** [comment]
@SimonSimCity can you confirm that it's fixed now?

**Comment by SimonSimCity** [comment]
As far as I could test now, it works smoothly 👍
